version: "3.9"

services:
  mobile.aautad.pt:
    container_name: mobile
    image: nextjs-app:latest
    environment:
      VIRTUAL_HOST: docs.aautad.pt
      LETSENCRYPT_HOST: docs.aautad.pt
    restart: always
    networks:
      - nginx_proxy_network

networks:
  nginx_proxy_network:
    external: true
    name: website_default # This might need to be adjusted